### ISSUE TITLE
Plugin is throwing an exception in Craft 3.1

### ISSUE THREAD

**Issue by internetztube** [craftcms/redactor#110]
```
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: settings'

in /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/craftcms/cms/src/services/Plugins.php:1323

Stack trace:
#0 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/craftcms/cms/src/services/Plugins.php(1323): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/home/forge/sta...', 1323, Array)
#1 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/craftcms/cms/src/services/Plugins.php(200): craft\services\Plugins->_getPluginConfigData('redactor')
#2 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/craftcms/cms/src/base/ApplicationTrait.php(1187): craft\services\Plugins->loadPlugins()
#3 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/craftcms/cms/src/console/Application.php(65): craft\console\Application->_postInit()
#4 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#5 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#6 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#7 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array)
#8 [internal function]: craft\console\Application->__construct(Array)
#9 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#10 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\console\\A...', Array, Array)
#11 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\console\\A...', Array, Array)
#12 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/craftcms/cms/bootstrap/bootstrap.php(252): yii\BaseYii::createObject(Array)
#13 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/vendor/craftcms/cms/bootstrap/console.php(31): require('/home/forge/sta...')
#14 /home/forge/stage.erecruiter.fredmansky.com/releases/e38042f801e7c454cde4667ece330210cfe32337/craft(22): require('/home/forge/sta...')
#15 {main}
```
https://github.com/craftcms/cms/blob/develop/src/services/Plugins.php#L1328

**Comment by andris-sevcenko** [comment]
This should be fixed with the release of Craft 3.1.1.

**Comment by internetztube** [comment]
When will it be released? @andris-sevcenko

**Comment by angrybrad** [comment]
@internetztube should be today!

**Comment by andris-sevcenko** [comment]
Closing as 3.1.3. has been released already.
