### ISSUE TITLE
One of Redactor’s migrations failed (m181101_110000_ids_in_settings_to_uids)

### ISSUE THREAD

**Issue by john-henry** [craftcms/redactor#112]
Already upgraded to Craft CMS 3.1.1 successfully.

Went ahead and tried to upgrade Redactor but one of the migrations failed

Volumes we use are all S3

Not using any Project Config as of yet

```
yii\base\ErrorException: Undefined index: availableVolumes

Migration: craft\redactor\migrations\m181101_110000_ids_in_settings_to_uids

Output:

Exception: Undefined index: availableVolumes (/.../vendor/craftcms/redactor/src/migrations/m181101_110000_ids_in_settings_to_uids.php:34)
#0 /.../vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/johnhenr...', 34)
#1 /.../vendor/craftcms/redactor/src/migrations/m181101_110000_ids_in_settings_to_uids.php(34): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/Users/johnhenr...', 34, Array)
#2 /.../vendor/craftcms/cms/src/db/Migration.php(56): craft\redactor\migrations\m181101_110000_ids_in_settings_to_uids->safeUp()
#3 /.../vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#4 /.../vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\redactor\migrations\m181101_110000_ids_in_settings_to_uids))
#5 /.../vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#6 /.../vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(445): craft\services\Updates->runMigrations(Array)
#7 /.../vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#8 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#9 /.../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /.../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /.../vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#12 /.../vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#13 /.../vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#14 /.../vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#15 /.../vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#16 /.../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /.../public/index.php(21): yii\base\Application->run()
#18 {main}
```

**Comment by carlcs** [comment]
Yeah it seems like `availableVolumes` wasn’t always required. I am not sure because we were also using import plugins on this install in the past, maybe incomplete settings data was caused by those and Craft and Redactor’s migrations aren’t responsible to guard against these issues?

**Comment by andris-sevcenko** [comment]
I'd say it's up to the migration to not assume too much and be more defensive :)

I'll fix this one today.
