### ISSUE TITLE
ArgumentCountError on entry save

### ISSUE THREAD

**Issue by Coysh** [craftcms/redactor#17]
Getting this error every time I save an entry with redactor field in the matrix:

> Too few arguments to function craft\base\Field::isValueEmpty(), 1 passed in /home/vagrant/sites/craft/vendor/craftcms/redactor/src/Field.php on line 314 and exactly 2 expected

Stack trace:
```
ArgumentCountError: Too few arguments to function craft\base\Field::isValueEmpty(), 1 passed in /home/vagrant/sites/craft/vendor/craftcms/redactor/src/Field.php on line 314 and exactly 2 expected in /home/vagrant/sites/craft/vendor/craftcms/cms/src/base/Field.php:311
Stack trace:
#0 /home/vagrant/sites/craft/vendor/craftcms/redactor/src/Field.php(314): craft\base\Field->isValueEmpty('<p>The OPC is a...')
#1 /home/vagrant/sites/craft/vendor/craftcms/cms/src/base/Element.php(1037): craft\redactor\Field->isValueEmpty(Object(craft\redactor\FieldData), Object(craft\elements\MatrixBlock))
#2 /home/vagrant/sites/craft/vendor/craftcms/cms/src/base/Element.php(776): craft\base\Element->isFieldEmpty('text')
#3 [internal function]: craft\base\Element->__call('isFieldEmpty:te...', Array)
#4 /home/vagrant/sites/craft/vendor/yiisoft/yii2/validators/Validator.php(444): call_user_func(Array, Object(craft\redactor\FieldData))
#5 /home/vagrant/sites/craft/vendor/yiisoft/yii2/validators/RequiredValidator.php(71): yii\validators\Validator->isEmpty(Object(craft\redactor\FieldData))
#6 /home/vagrant/sites/craft/vendor/yiisoft/yii2/validators/Validator.php(281): yii\validators\RequiredValidator->validateValue(Object(craft\redactor\FieldData))
#7 /home/vagrant/sites/craft/vendor/yiisoft/yii2/validators/Validator.php(267): yii\validators\Validator->validateAttribute(Object(craft\elements\MatrixBlock), 'field:text')
#8 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\MatrixBlock), Array)
#9 /home/vagrant/sites/craft/vendor/craftcms/cms/src/fields/Matrix.php(527): yii\base\Model->validate()
#10 /home/vagrant/sites/craft/vendor/craftcms/cms/src/base/Element.php(1019): craft\fields\Matrix->validateBlocks(Object(craft\elements\Entry), NULL)
#11 [internal function]: craft\base\Element->validateCustomFieldAttribute('field:indexBody', Array, Object(yii\validators\InlineValidator))
#12 /home/vagrant/sites/craft/vendor/yiisoft/yii2/validators/InlineValidator.php(72): call_user_func(Array, 'field:indexBody', Array, Object(yii\validators\InlineValidator))
#13 /home/vagrant/sites/craft/vendor/yiisoft/yii2/validators/Validator.php(267): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'field:indexBody')
#14 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#15 /home/vagrant/sites/craft/vendor/craftcms/cms/src/services/Elements.php(373): yii\base\Model->validate()
#16 /home/vagrant/sites/craft/vendor/craftcms/cms/src/controllers/EntriesController.php(539): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#17 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#18 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#20 /home/vagrant/sites/craft/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('save-entry', Array)
#21 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#22 /home/vagrant/sites/craft/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('entries/save-en...', Array)
#23 /home/vagrant/sites/craft/vendor/craftcms/cms/src/web/Application.php(445): craft\web\Application->runAction('entries/save-en...', Array)
#24 /home/vagrant/sites/craft/vendor/craftcms/cms/src/web/Application.php(221): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#25 /home/vagrant/sites/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#26 /home/vagrant/sites/craft/public/index.php(17): yii\base\Application->run()
#27 {main}
```

**Comment by brandonkelly** [comment]
Thanks!
