### ISSUE TITLE
Broken update; Internal Server Error

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/redactor#252]
# Description

I ran the update from the prior version to the new 2.7; everything else was up-to-date.
Totally screwed.

# Steps to reproduce

1. Update the plugin

<img width="745" alt="Screen Shot 2020-08-10 at 20 08 57" src="https://user-images.githubusercontent.com/814039/89821118-036ead00-db46-11ea-9075-5dcf85bdee76.png">

# Additional info

```
Status: Internal Server Error

Response: <pre>Exception (Invalid Configuration) &#039;yii\base\InvalidConfigException&#039; with message &#039;Failed to instantiate component or class &quot;yii\shell\Bootstrap&quot;.&#039;

in /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/di/Container.php:449

Stack trace:
#0 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/di/Container.php(374): yii\di\Container-&gt;getDependencies(&#039;yii\\shell\\Boots...&#039;)
#1 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container-&gt;build(&#039;yii\\shell\\Boots...&#039;, Array, Array)
#2 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container-&gt;get(&#039;yii\\shell\\Boots...&#039;, Array)
#3 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/base/Application.php(294): yii\BaseYii::createObject(&#039;yii\\shell\\Boots...&#039;)
#4 /Users/matt/Sites/_bwp/craft/vendor/craftcms/cms/src/web/Application.php(121): yii\base\Application-&gt;bootstrap()
#5 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/base/Application.php(273): craft\web\Application-&gt;bootstrap()
#6 /Users/matt/Sites/_bwp/craft/vendor/craftcms/cms/src/web/Application.php(102): yii\base\Application-&gt;init()
#7 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application-&gt;init()
#8 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject-&gt;__construct(Array)
#9 /Users/matt/Sites/_bwp/craft/vendor/craftcms/cms/src/web/Application.php(92): yii\base\Application-&gt;__construct(Array)
#10 [internal function]: craft\web\Application-&gt;__construct(Array)
#11 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass-&gt;newInstanceArgs(Array)
#12 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container-&gt;build(&#039;craft\\web\\Appli...&#039;, Array, Array)
#13 /Users/matt/Sites/_bwp/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container-&gt;get(&#039;craft\\web\\Appli...&#039;, Array, Array)
#14 /Users/matt/Sites/_bwp/craft/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#15 /Users/matt/Sites/_bwp/craft/vendor/craftcms/cms/bootstrap/web.php(51): require(&#039;/Users/matt/Sit...&#039;)
#16 /Users/matt/Sites/_bwp/public/index.php(20): require(&#039;/Users/matt/Sit...&#039;)
#17 {main}</pre>
```

## Application Info

PHP version	7.1.33
OS version	Darwin 17.7.0
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.1.33
Craft edition & version	Craft Solo 3.5.2
Yii version	2.0.36
Twig version	2.12.5
Guzzle version	6.5.5
Imagine version	1.2.3-dev

## Plugins

Dumper	2.0.0
Eager Beaver	1.0.4
Empty Coalesce	1.0.6
Field Manager	2.1.8
Imager	v2.4.0
Image Resizer	2.0.10
Inlin	2.1.1
Maps	3.8.4.1
Minify	1.2.10
Redactor	2.6.1
SEOmatic	3.3.13
Similar	1.0.6
Table Maker	2.0.1
Twig Profiler	1.0.1

**Comment by angrybrad** [comment]
@MattWilcox We _just_ deployed a workaround for this on our end. Can you restore from a pre-update attempt database backup and composer.json file and try again?

**Comment by MattWilcox** [comment]
Yep, confirmed that is now working as expected - thanks Brad 👍
