### ISSUE TITLE
Errors since 2.9.0

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/redactor#355]
### Description

Seeing these errors with the latest update:

```


PHP Warning 'yii\base\ErrorException' with message 'Undefined array key 3'
--
  |  
  | in /app/user/vendor/craftcms/redactor/src/Field.php:687
  |  
  | Stack trace:
  | #0 /app/user/vendor/craftcms/redactor/src/Field.php(687): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/app/user/vendo...', 687)
  | #1 [internal function]: craft\redactor\Field->craft\redactor\{closure}(Array)
  | #2 /app/user/vendor/craftcms/redactor/src/Field.php(685): preg_replace_callback('/(href=\|src=)([...', Object(Closure), '\n <p>\n <strong>...')
  | #3 /app/user/vendor/craftcms/cms/src/base/Element.php(2134): craft\redactor\Field->serializeValue('\n <p>\n <strong>...', Object(craft\elements\Entry))
  | #4 /app/user/vendor/yiisoft/yii2/validators/InlineValidator.php(84): craft\base\Element->validateCustomFieldContentSize('serviceText', NULL, Object(yii\validators\InlineValidator), Object(craft\redactor\FieldData))
  | #5 /app/user/vendor/yiisoft/yii2/validators/Validator.php(261): yii\validators\InlineValidator->validateAttribute(Object(craft\elements\Entry), 'serviceText')
  | #6 /app/user/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
  | #7 /app/user/vendor/craftcms/cms/src/services/Elements.php(2536): yii\base\Model->validate()
  | #8 /app/user/vendor/craftcms/cms/src/services/Elements.php(784): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, true, false)
  | #9 /app/user/vendor/craftcms/cms/src/test/fixtures/elements/BaseContentFixture.php(154): craft\services\Elements->saveElement(Object(craft\elements\Entry), true, true, false)
  | #10 /app/user/vendor/craftcms/cms/src/test/fixtures/elements/BaseContentFixture.php(83): craft\test\fixtures\elements\BaseContentFixture->saveElement(Object(craft\elements\Entry))
  | #11 /app/user/vendor/yiisoft/yii2/test/FixtureTrait.php(96): craft\test\fixtures\elements\BaseContentFixture->load()
  | #12 /app/user/vendor/yiisoft/yii2/console/controllers/FixtureController.php(159): yii\console\controllers\FixtureController->loadFixtures(Array)
  | #13 [internal function]: yii\console\controllers\FixtureController->actionLoad(Array)
  | #14 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
  | #15 /app/user/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
  | #16 /app/user/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('load', Array)
  | #17 /app/user/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('load', Array)
  | #18 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('fixture/load', Array)
  | #19 /app/user/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('fixture/load', Array)
  | #20 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('fixture/load', Array)
  | #21 /app/user/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
  | #22 /app/user/craft(24): yii\base\Application->run()
  | #23 {main}


```

### Steps to reproduce

1. I'm using fixtures that have "a's" with empy href's

### Additional info

- Craft version: 3.7.30.1
- PHP version: 8.0.14
- Database driver & version: PostgreSQL 13.5
- Plugins & versions: Redactor 2.9.0

**Comment by andris-sevcenko** [comment]
Thanks for reporting - just fixed it for the next release!

**Comment by boboldehampsink** [comment]
@andris-sevcenko thanks for the fix. Any eta on release so we can start using 2.9?

**Comment by andris-sevcenko** [comment]
About a minute ago!
